
[env:firebeetle32]
platform = espressif32
board = firebeetle32
framework = arduino

lib_deps =
  adafruit/Adafruit BME280 Library @ ^2.2.4
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  seeed-studio/Grove - Laser PM2.5 Sensor HM3301 @ ^1.0.2
  mcci-catena/MCCI LoRaWAN LMIC library @ ^4.1.1

build_flags =
  -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
  -I lib/lmic_config

monitor_speed = 115200